<?php

/* custom routes generated by CRUD */

Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('locations', ['as'=> 'locations.index', 'uses' => 'LocationController@index']);
Route::post('locations', ['as'=> 'locations.store', 'uses' => 'LocationController@store']);
Route::get('locations/create', ['as'=> 'locations.create', 'uses' => 'LocationController@create']);
Route::put('locations/{locations}', ['as'=> 'locations.update', 'uses' => 'LocationController@update']);
Route::patch('locations/{locations}', ['as'=> 'locations.update', 'uses' => 'LocationController@update']);
Route::get('locations/{id}/delete', array('as' => 'locations.delete', 'uses' => 'LocationController@getDelete'));
Route::get('locations/{id}/confirm-delete', array('as' => 'locations.confirm-delete', 'uses' => 'LocationController@getModalDelete'));
Route::get('locations/{locations}', ['as'=> 'locations.show', 'uses' => 'LocationController@show']);
Route::get('locations/{locations}/edit', ['as'=> 'locations.edit', 'uses' => 'LocationController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('statuses', ['as'=> 'statuses.index', 'uses' => 'StatusController@index']);
Route::post('statuses', ['as'=> 'statuses.store', 'uses' => 'StatusController@store']);
Route::get('statuses/create', ['as'=> 'statuses.create', 'uses' => 'StatusController@create']);
Route::put('statuses/{statuses}', ['as'=> 'statuses.update', 'uses' => 'StatusController@update']);
Route::patch('statuses/{statuses}', ['as'=> 'statuses.update', 'uses' => 'StatusController@update']);
Route::get('statuses/{id}/delete', array('as' => 'statuses.delete', 'uses' => 'StatusController@getDelete'));
Route::get('statuses/{id}/confirm-delete', array('as' => 'statuses.confirm-delete', 'uses' => 'StatusController@getModalDelete'));
Route::get('statuses/{statuses}', ['as'=> 'statuses.show', 'uses' => 'StatusController@show']);
Route::get('statuses/{statuses}/edit', ['as'=> 'statuses.edit', 'uses' => 'StatusController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('locationStatuses', ['as'=> 'locationStatuses.index', 'uses' => 'Location_statusController@index']);
Route::post('locationStatuses', ['as'=> 'locationStatuses.store', 'uses' => 'Location_statusController@store']);
Route::get('locationStatuses/create', ['as'=> 'locationStatuses.create', 'uses' => 'Location_statusController@create']);
Route::put('locationStatuses/{locationStatuses}', ['as'=> 'locationStatuses.update', 'uses' => 'Location_statusController@update']);
Route::patch('locationStatuses/{locationStatuses}', ['as'=> 'locationStatuses.update', 'uses' => 'Location_statusController@update']);
Route::get('locationStatuses/{id}/delete', array('as' => 'locationStatuses.delete', 'uses' => 'Location_statusController@getDelete'));
Route::get('locationStatuses/{id}/confirm-delete', array('as' => 'locationStatuses.confirm-delete', 'uses' => 'Location_statusController@getModalDelete'));
Route::get('locationStatuses/{locationStatuses}', ['as'=> 'locationStatuses.show', 'uses' => 'Location_statusController@show']);
Route::get('locationStatuses/{locationStatuses}/edit', ['as'=> 'locationStatuses.edit', 'uses' => 'Location_statusController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('locationStatuses', ['as'=> 'locationStatuses.index', 'uses' => 'LocationStatusController@index']);
Route::post('locationStatuses', ['as'=> 'locationStatuses.store', 'uses' => 'LocationStatusController@store']);
Route::get('locationStatuses/create', ['as'=> 'locationStatuses.create', 'uses' => 'LocationStatusController@create']);
Route::put('locationStatuses/{locationStatuses}', ['as'=> 'locationStatuses.update', 'uses' => 'LocationStatusController@update']);
Route::patch('locationStatuses/{locationStatuses}', ['as'=> 'locationStatuses.update', 'uses' => 'LocationStatusController@update']);
Route::get('locationStatuses/{id}/delete', array('as' => 'locationStatuses.delete', 'uses' => 'LocationStatusController@getDelete'));
Route::get('locationStatuses/{id}/confirm-delete', array('as' => 'locationStatuses.confirm-delete', 'uses' => 'LocationStatusController@getModalDelete'));
Route::get('locationStatuses/{locationStatuses}', ['as'=> 'locationStatuses.show', 'uses' => 'LocationStatusController@show']);
Route::get('locationStatuses/{locationStatuses}/edit', ['as'=> 'locationStatuses.edit', 'uses' => 'LocationStatusController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('fileStatuses', ['as'=> 'fileStatuses.index', 'uses' => 'FileStatusController@index']);
Route::post('fileStatuses', ['as'=> 'fileStatuses.store', 'uses' => 'FileStatusController@store']);
Route::get('fileStatuses/create', ['as'=> 'fileStatuses.create', 'uses' => 'FileStatusController@create']);
Route::put('fileStatuses/{fileStatuses}', ['as'=> 'fileStatuses.update', 'uses' => 'FileStatusController@update']);
Route::patch('fileStatuses/{fileStatuses}', ['as'=> 'fileStatuses.update', 'uses' => 'FileStatusController@update']);
Route::get('fileStatuses/{id}/delete', array('as' => 'fileStatuses.delete', 'uses' => 'FileStatusController@getDelete'));
Route::get('fileStatuses/{id}/confirm-delete', array('as' => 'fileStatuses.confirm-delete', 'uses' => 'FileStatusController@getModalDelete'));
Route::get('fileStatuses/{fileStatuses}', ['as'=> 'fileStatuses.show', 'uses' => 'FileStatusController@show']);
Route::get('fileStatuses/{fileStatuses}/edit', ['as'=> 'fileStatuses.edit', 'uses' => 'FileStatusController@edit']);

});
